= The SONAR-netCDF4 convention for sonar data


This directory contains the text and source files necessary to generate the SONAR-netCDF4 convention. 

It is also the place where new versions of the convention are discussed and developed.

Version 1.0 of the SONAR-netCDF4 convention (as ICES CRR No. 341) is available http://www.ices.dk/sites/pub/Publication%20Reports/Cooperative%20Research%20Report%20(CRR)/CRR341.pdf[here].

== Ongoing and future developments

A version 2 of the convention is currently under development to support more types of active acoustic equipment and to store summarised versions of the acoustic data. The additional types of equipment that will be supported are:

- multi-beam bathymetric sonars, 
- acoustic doppler current profilers (ADCP), and 
- echosounders.

Support for split-aperture, multi-frequency/channel, and broadband data is also under development.

Support for summarised versions of acoustic data are currently focused on gridded datasets from echosounders, intended to make large scale processing of data easier (e.g., machine learning).

As these changes are added to the main convention document, the *Ongoing and future developments* section of that document is updated to provide a summmary of what has changed.

A preview of the latest working draft is available https://gitcdn.link/repo/ices-publications/SONAR-netCDF4/master/Formatted_docs/crr341.html[here] (note that it can take up to 2 hours for new changes to appear).

image::https://github.com/ices-publications/SONAR-netCDF4/workflows/BuildDocuments/badge.svg[Embedded]
 
== Suggestions and contributions welcome
WGFAST welcomes suggestions, discussion, and contributions to this SONAR netCDF-4 convention.

Before submitting a pull request, please take a moment to find out whether your idea fits within the scope and aims of the convention, and whether your idea can be achieved within the existing SONAR netCDF-4 convention. It is your role to adequately explain and justify the merits of what you want. Please provide as much detail and context as possible. Good pull requests remain focused in scope and avoid containing unrelated commits.

*Please ask the convention coordinators before starting on any _significant_ edits*. Otherwise you risk spending a lot of time working on something that the convention coordinators might not want to merge into the project.

== How to contribute
The metadata convention is written in AsciiDoc markup language. Suggestions, discussions, and contributions are done through the facilities provided by GitHub. Please use the https://github.com/ices-publications/SONAR-netCDF4/issues[issue tracker] for suggestions and discussions, and create https://github.com/ices-publications/SONAR-netCDF4/pulls[pull requests] for contributions.

For guidance on Git, GitHub, and AsciiDoc syntax, as well as the suggested Git workflow for contributors, please refer to documents in the https://github.com/ices-eg/wg_WGFAST/tree/master/How_to_contribute[How to contribute] folder.
